"""Python decoder for the GameRecord binary stream (training records).

Mirrors ``src/core/GameRecord.cpp`` exactly; the C++ encoder is the single
source of truth for the byte layout and this module must never drift from it.
Standard library only — no numpy, no torch — so the decoder and its gate run
anywhere.

Byte layout (all little-endian)::

    Stream      := magic[9] "GOMOKUREC"  u32 version(=1)  Game*
    Game        := u32 numPositions  PositionRecord[numPositions]
    PositionRecord := f32 planes[900]  f32 policy[225]  f32 value

``planes`` are the network input exactly as ``BoardEncoder::encode`` emits
(4 planes of 15x15, channel-major, each plane row-major); ``policy`` is a
probability distribution over cells (row-major, sums to 1); ``value`` is the
outcome from the player-to-move's perspective (+1 win, -1 loss, 0 draw).

Only the **decoder** is needed by the trainer (self-play data is generated by
the C++ tools). ``encode_stream`` exists purely so the round-trip gate can
prove the Python side understands the format byte-for-byte.
"""

from __future__ import annotations

import dataclasses
import struct

MAGIC = b"GOMOKUREC"
VERSION = 1

PLANES = 900
POLICY = 225
POSITION_FLOATS = PLANES + POLICY + 1  # 1126
POSITION_BYTES = POSITION_FLOATS * 4  # 4504

HEADER_SIZE = len(MAGIC) + struct.calcsize("<I")  # 13


@dataclasses.dataclass
class PositionRecord:
    """One training position: input planes, policy target, outcome value."""

    planes: list[float]  # 4 * 15 * 15 = 900
    policy: list[float]  # 225
    value: float


def decode_stream(data: bytes) -> list[list[PositionRecord]]:
    """Decode a record stream into ``[[PositionRecord, ...], ...]`` (games).

    Raises ``ValueError`` on any malformed input: bad magic, unsupported
    version, a truncated header/position, a ``numPositions`` that overruns the
    buffer, or trailing bytes that do not form a game.
    """
    if len(data) < HEADER_SIZE:
        raise ValueError("truncated stream header")
    if data[: len(MAGIC)] != MAGIC:
        raise ValueError("bad magic")
    (version,) = struct.unpack_from("<I", data, len(MAGIC))
    if version != VERSION:
        raise ValueError(f"unsupported version {version}")

    games: list[list[PositionRecord]] = []
    off = HEADER_SIZE
    while off < len(data):
        if off + struct.calcsize("<I") > len(data):
            raise ValueError("truncated numPositions")
        (num_positions,) = struct.unpack_from("<I", data, off)
        off += struct.calcsize("<I")
        need = num_positions * POSITION_BYTES
        if off + need > len(data):
            raise ValueError("numPositions exceeds the remaining buffer")

        game: list[PositionRecord] = []
        for _ in range(num_positions):
            values = struct.unpack_from(f"<{POSITION_FLOATS}f", data, off)
            off += POSITION_BYTES
            game.append(
                PositionRecord(
                    planes=list(values[:PLANES]),
                    policy=list(values[PLANES : PLANES + POLICY]),
                    value=values[PLANES + POLICY],
                )
            )
        games.append(game)
    return games


def encode_stream(games: list[list[PositionRecord]]) -> bytes:
    """Encode decoded games back to a byte stream (round-trip test only).

    The trainer never encodes; this exists so the gate can prove the Python
    decoder matches the C++ byte layout exactly.
    """
    out = bytearray()
    out += MAGIC
    out += struct.pack("<I", VERSION)
    for game in games:
        out += struct.pack("<I", len(game))
        for pos in game:
            if len(pos.planes) != PLANES or len(pos.policy) != POLICY:
                raise ValueError("PositionRecord has the wrong field sizes")
            out += struct.pack(f"<{PLANES}f", *pos.planes)
            out += struct.pack(f"<{POLICY}f", *pos.policy)
            out += struct.pack("<f", pos.value)
    return bytes(out)


def decode_file(path: str) -> list[list[PositionRecord]]:
    """Decode a record stream from a file path."""
    with open(path, "rb") as f:
        return decode_stream(f.read())
